// This file is auto-generated by `npx convex dev`.
// It will be overwritten when you run `npx convex dev` with a live Convex project.
// This stub provides a typed `internal` export for local TypeScript checking.
import type { AnyApi } from "convex/server";

export const internal: AnyApi = {} as AnyApi;
export const api: AnyApi = {} as AnyApi;
