// This file is auto-generated by `npx convex dev`.
// It will be overwritten when you run `npx convex dev` with a live Convex project.
// This stub re-exports the generic Convex functions for local TypeScript checking.
export {
  queryGeneric as query,
  mutationGeneric as mutation,
  internalActionGeneric as internalAction,
  internalMutationGeneric as internalMutation,
  internalQueryGeneric as internalQuery,
  actionGeneric as action,
} from "convex/server";
